### ISSUE TITLE
git.py nem írja ki a hibákat!

### ISSUE THREAD

**Issue by hajasattila** [l-janos/Gyakorlas#6]
### Kapott eredmény: "Hello World"

**Javításra szorul!**

### Issue létrehozva: 2024.03.27 19:00

![image](https://github.com/l-janos/Gyakorlas/assets/64254833/f4ac564e-7163-4740-a3e5-7d21ebed3f29)

**Comment by l-janos** [comment]
https://github.com/l-janos/Gyakorlas/tree/FIX/issue-6/numberFixing
